### PR TITLE
Magpie20 zeppelin 0.8.0

### PR DESCRIPTION
**Pull request by bpanneton**
Added in Zeppelin 0.8.0

### CODE REVIEW

**Comment by bpanneton** [comment]
Corrected base.

**Comment by chu11** [comment]
I hate to be a bother, but could this be done on the master branch.  Then I will rebase and it'll get put into the magpie 2.0 branch.

**Comment by bpanneton** [comment]
Yep! I will do that soon.

**Comment by bpanneton** [comment]
Separated Zeppelin 0.8.0 and Magpie20 fix

**Pull request closed without merging**
