### PR TITLE
Added support to allow other sytem users to use the Yarn default queue

### PR DESCRIPTION
**Pull request by bpanneton**

### CODE REVIEW

**Comment by chu11** [comment]
in principle the feature is fine, but given this is a security issue I'd prefer if it were not available for users by default.  How about this being an optional build via a Makefile option in ```submission-scripts/templates/Makefile```?  In other words, by default ```YARN_QUEUES_EXTRA_USERS``` and ```YARN_QUEUES_EXTRA_GROUPS``` aren't generated and put into submission files.

**Comment by chu11** [comment]
and instead of this added to README.hadoop as step 4, it can just be a special extra feature.  You can mention in a separate section of README.hadoop.

**Comment by bpanneton** [comment]
I moved it in the README and removed it from the submission-scripts. I figured advanced users can manually add it in if they need it.

**Comment by chu11** [comment]
Overall looks good, but I noticed

```
yarnqueueusers="${yarnqueueusers},${YARN_QUEUES_EXTRA_USERS}"
...
yarnqueueusers="${yarnqueueusers} ${YARN_QUEUES_EXTRA_GROUPS}"
```

one is comma separated and one is space separated, probably a typo somewhere there?

**Comment by bpanneton** [comment]
Nope, that is how it should be. The variable ends up with a space separating the users and the groups. Users are comma combined and Groups are comma combined.

**Pull request merged**
