### PR TITLE
Updated Spark 2.0 paths from lib to jars corresponding to package cha…

### PR DESCRIPTION
**Pull request by bpanneton**
…nges

### CODE REVIEW

**Comment by chu11** [comment]
This should probably be done based on the SPARK_VERSION, not just assuming "jars" dir?  right?  So code like in magpie-setup-project-spark would probably work

```
    # Handle special settings depending on version
    # 0 is =, 1 is >, 2 is <
    Magpie_vercomp ${magpie_sparkmajorminorversion} 2.0
    vercomp_result=$?
    if [ "${vercomp_result}" == "0" ] || [ "${vercomp_result}" == "1" ]
    then
         .... blah
    else
         ..... blah
    fi
```

**Comment by bpanneton** [comment]
That is a good point. I will fix it up.

**Comment by bpanneton** [comment]
Should be good now.

**Comment by chu11** [comment]
I don't think $magpie_sparkmajorminorversion been set appropriately?  You have to call `Magpie_get_spark_major_minor_version`

**Comment by bpanneton** [comment]
Third time is the charm!

**Comment by chu11** [comment]
LGTM, thanks

**Pull request merged**
