### PR TITLE
Sleep cleanup

### PR DESCRIPTION
**Pull request by bpanneton**

### CODE REVIEW

**Comment by chu11** [comment]
doh! good catch.

in general looks fine, but I think at most there should be only one pid in ```sleep-pids``` at any point in time?  So there's no reason to append to it?  And thus no need for the loop in magpie-run?

**Comment by bpanneton** [comment]
Doing a quick search revealed the following locations where a new sleep was created. I did that because I figured it would be safer. If you want I can just make it occur in the normal mode. Either way works for me.

magpie/run/magpie-run-project-hbase:        ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &                                                                                                                                
magpie/run/magpie-run-project-zookeeper:        ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &                                                                                                                            
magpie/run/magpie-run-execute:    ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &                                                                                                                                          
magpie/run/magpie-run-execute:    ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep normal &                                                                                                                                             
magpie/run/magpie-run-project-kafka:        ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &                                                                                                                                
magpie/run/magpie-run-project-phoenix:        ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &                                                                                                                              
magpie/run/magpie-run-project-tachyon:        ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &                                                                                                                              
magpie/run/magpie-run-project-zeppelin:        ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &                                                                                                                             
magpie/run/magpie-run-project-storm:        ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &                                                                                                                                
magpie/run/magpie-run-project-spark:        ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &                                                                                                                                
magpie/run/magpie-run-project-hadoop:        ${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-sleep countdown &

**Comment by chu11** [comment]
So we're on the same page, when you say "job is interrupted early", you're referring to when the user uses the  "kill -s 10 <some pid output from magpie>"?  Or do you mean when someone cancels the job, like with scancel in slurm?  B/c I'm sort of confused now.

The two sleeps in magpie-run-execute should be managed properly for the "kill -s 10" case, so that should include the interactive case (originally we didn't background the sleep call, so killing the parent magpie-job-sleep should be enough?).

The majority of the project job sleeps (e.g. magpie-run-project-hadoop) are when the user is entering setuponly mode.  So the "kill -s 10" case doesn't apply.

**Comment by bpanneton** [comment]
On our cluster scancel does not kill any of the running processes. However I am talking about when the job mode is set to 'interactive' and you run the kill -s 10 call. It doesn't clean up the sleeps on our machine.  I wrote a simplified example of what I am seeing and it boggles my mind:

-bash-4.2$ cat ~/master_test.sh
#!/bin/bash
~/test.sh &
wait $!

-bash-4.2$ cat ~/test.sh
#!/bin/bash
sleep 100 

NOTE: Start ~/master_test.sh in a different terminal

-bash-4.2$ ps -ef | grep test.sh
panneton 26932  5498  0 17:22 pts/3    00:00:00 /bin/bash /usr/people/panneton/master_test.sh
panneton 26933 26932  0 17:22 pts/3    00:00:00 /bin/bash /usr/people/panneton/test.sh
panneton 27157 23483  0 17:22 pts/5    00:00:00 grep --color=auto test.sh

-bash-4.2$ ps -ef | grep sleep
panneton 26934 26933  0 17:22 pts/3    00:00:00 sleep 100
panneton 27225 23483  0 17:22 pts/5    00:00:00 grep --color=auto sleep

-bash-4.2$ kill 26933

-bash-4.2$ ps -ef | grep sleep
panneton 26934     1  0 17:22 pts/3    00:00:00 sleep 100
panneton 27569 23483  0 17:22 pts/5    00:00:00 grep --color=auto sleep

-bash-4.2$ ps -ef | grep test.sh
panneton 27681 23483  0 17:23 pts/5    00:00:00 grep --color=auto test.sh

-bash-4.2$ 

Thus the cleanup that you do in fact do doesn't actually clean up our sleeps. Can you verify that this doesn't occur on your machine as well with the two simple scripts. I'm lost as to what would cause this. I will continue to investigate.

**Comment by bpanneton** [comment]
Ah! We need to kill the process group rather than the parent. "kill -- -<pid>", so in my case rather than kill 26933 I should have done "kill -- -26933". I will clean this up in the patch.

**Comment by chu11** [comment]
Yeah, I figured it out at about the same time taht it should be process groups.  I'm not super familiar with process group management but:

```
>ps -e -o pid,ppid,pgid,comm | grep sleep
176021 176017 176013 sleep

>ps -e -o pid,ppid,pgid,comm | grep test
176013 131450 176013 master_test.sh
176017 176013 176013 test.sh
```

in this case for me, all three are in one process group.  I think we're looking for a process group of just test & sleep.

**Comment by bpanneton** [comment]
Yea, that is what I was running into. We don't want the master_test.sh to die. It might be easier to just go a similar route that I was originally and track the pids of the sleeps that get created. 

Something like this should work. I'll test it and create a patch.
for pid in $(pstree -cp ${childpid} | grep -Po '\(\K\d+' | sed -re 's/$/ /g'); do kill $pid; done

**Comment by chu11** [comment]
there's gotta be something simpler than pstree & that regex, right?  Minimally with ```ps``` you can pass the --ppid option.  I can research a bit online.

**Comment by bpanneton** [comment]
I had hoped. I tried with ps and --ppid but I was unable to get just the child and its grandchild. I either got the parent, child and grandchild or just the child. The patch I just push will work, but if we can find a better option I agree with you.

**Comment by chu11** [comment]
ah, i see why you did it that way.  LGTM, thanks!

**Pull request merged**
