### PR TITLE
Yarn mem check

### PR DESCRIPTION
**Pull request by bpanneton**

### CODE REVIEW

**Comment by bpanneton** [comment]
Rebased

**Comment by chu11** [comment]
overall looks fine, although should there be some more text here about when users might use these options?

```
Should physical and virtual memory limits be enforced for containers.
Defaults to true
```

I'm not too knowledgeable of the need.  Googling, I'm guessing some users may launch other services in a Hadoop container, which will surpass those limits but are really ok?

**Comment by bpanneton** [comment]
I am running on Centos which is pretty aggressive on allocating vmem within the OS. It would cause my container to be killed because it would exceed the vmem to pmem ratio even though it was still safe. I'm sure there are other situations where this would be needed as well.

**Comment by chu11** [comment]
LGTM. travis seemed to get stuck and couldn't run, restarted it.  Can click merge once that's done.

**Pull request merged**
