### PR TITLE
Documentation unification

### PR DESCRIPTION
**Pull request by pgrabusz**

### CODE REVIEW

**Comment by chu11** [comment]
Thanks for the PR.  Just skimming, it seems you simply metadata-ized the documentation?  I'll have to look through the files, but a few didn't seem to turn out correctly.  Such as README.no-local-dir.md

I think that metadata-izing the doc/logo files was probably unnecessary as they are just copyright information on the jpgs and the formatting seems to be off as a result.

**Comment by pgrabusz** [comment]
@chu11 thank you for your quick response!

First of all, I would like to point out that this is only my proposal for changes that can be made and if everything was cleaner and worked better w/o such changes feel free to reject this PR :)

Yes, most changes were made to make the files showing up correctly in GitHub's default viewer.
I also did some smaller changes like removing double spaces.

GitHub uses Markdown (https://en.wikipedia.org/wiki/Markdown) syntax for the documentation.
In addition, files should have ".md" extension to be parsed and shown in the "user-friendly" way.
Here's the cheat sheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet.

Could you please point me the places where something went wrong so I can fix it? You mentioned about README.no-local-dir.md but it works just fine for me: https://github.com/Intel-SolutionDev/magpie/blob/doc-unify/doc/README.no-local-dir.md

Maybe you are using some other application as a viewer? If so, could you please point me what?

Thank you for your time,
Piotr

**Comment by chu11** [comment]
I think getting every metadata-ized is a good idea, I've been lazy on that front, so I appreciate the effort.  I'll look through the files and give a review.  I'm sure 90+% of it is fine and it's just a few odd things here and there.

For ```README.no-local-dir.md``` I expected the chunk in the middle to be a list instead of preformatted (I only now looked at the raw file).

I'll go through the files 1 by 1 and see how they look and give a review.

**Comment by pgrabusz** [comment]
Great to hear :) thank you!

**Comment by chu11** [comment]
Overall looks pretty good.  I think the pre-formatted chunk in the middle of ```README.no-local-dir.md``` should be a unordered list (or just normal text) vs pre-formatted.  I tend to think of command line examples and example output as what gets pre-formatted.  Feel free to reformat the area if you think it should just be reformatted.

I'd also un-metadata the `README.magpielogo` files, b/c those are clearly not documentation.  They are more just copyright info.  Or do you think the files should be renamed?

**Comment by pgrabusz** [comment]
I don't think changes are still valid. Closing.

**Pull request closed without merging**
